name: 'Dispatch Suggestor'
description: 'Suggests dispatchable workflows for a branch that would otherwise trigger the dispatchable workflows from pushes to the trunk.'
author: 'Nathan Levett'
branding:
  icon: 'sunrise'  
  color: 'purple'
inputs:
  github_token:
    description: 'Requires `permissions: { actions: read, contents: read, pull-requests: read }`'
    required: true
  trunk-branch:
    description: 'Name of the trunk branch, if not main'
    required: false
    default: 'main'
  checkout-root:
    description: 'The path to the root folder of the checked out repo, relative to the default working-directory, `$GITHUB_WORKSPACE`. Should be the same as the value provided to `@actions/checkout` `with.path:`, or default.'
    required: false
    default: '.'
  log-event-payload:
    description: 'If not false, will print the whole triggering event payload.'
    required: false
    default: 'false'
  log-workflow-triggers:
    description: 'If not false, will print the triggers for all dispatchable workflows.'
    required: false
    default: 'false'
outputs:
  list-of-changed-files:
    description: 'A list of the files that have been touched by this PR'
  list-of-dispatchable-workflows:
    description: 'A list of the workflows found in this repo that have workflow_dispatch triggers.'
runs:
  using: 'node20'
  main: 'dist/action.js'
