name: Action
on:
  pull_request:
defaults:
  run:
    shell: bash
# permissions: {} # swap to when public
jobs:
  test:
    name: Test the Action
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        sparse-checkout: |
          action.yml
          dist/index.js
        sparse-checkout-cone-mode: false
    - name: Use the action
      uses: ./
      id: action-use
      with:
        name-of-input: 'Yikes'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the output time
      run: echo "The time was ${{ steps.action-use.outputs.name-of-output }}"
