name: Test Lint Verify
on:
  push:
defaults:
  run:
    shell: bash
permissions: {}
jobs:
  test:
    permissions:
      contents: read
    name: Test List Verify
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      # with: # apply these when testing how it works externally
      #   sparse-checkout: .github/workflows
      #   sparse-checkout-cone-mode: false
    - name: 🟨🟦🟩🟥 Set up Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: './.nvmrc'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: 🧱 Install build dependencies
      run: make setup
    - name: 🦂 Test
      run: make test
    - name: 🧹 Lint
      run: make lint
    - name: ⚖ Does the checked in JS match the transpiled TS? 
      run: make verify_transpiled_checkin
